[package]
name = "rust_lib_dart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gluesql-core.workspace = true
gluesql_memory_storage.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
] }
rust_decimal = { version = "1", features = ["serde-str"] }
flutter_rust_bridge = { version = "=2.0.0-dev.40", features = ["chrono"] }
thiserror = "1.0"
ordered-float = { version = "4", features = ["serde"] }
# gluesql-core = "0.15.0"
# gluesql_memory_storage = "0.15.0"
