[package]
name = "memory-storage"
version = "0.9.0"
edition = "2021"

[dependencies]
gluesql-core = { path = "../../core", features = [
	"alter-table",
	"index",
	"transaction",
	"metadata",
] }

async-trait = "0.1"

[dev-dependencies]
test-suite = { path = "../../test-suite", features = [
	"alter-table",
	"index",
	"transaction",
	"metadata",
] }

tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
