[package]
name = "gluesql-parquet-storage"
authors = ["MeenSeek Kim <meenseek5929@naver.com>"]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
thiserror = "1.0"
parquet = "43.0.0"
byteorder = "1.4.3"
num-traits = "0.2.5"
rust_decimal = "1.15"
lazy_static = "1.4.0"

[dev-dependencies]
test-suite.workspace = true
uuid = "1"
