[package]
name = "gluesql_sled_storage"
version = "0.10.1"
edition = "2021"
authors = ["Taehoon Moon <taehoon.moon@outlook.com>"]
description = "GlueSQL - Open source SQL database engine fully written in Rust with pure functional execution layer, easily swappable storage and web assembly support!"
license = "Apache-2.0"
repository = "https://github.com/gluesql/gluesql"
documentation = "https://docs.rs/gluesql/"

[dependencies]
gluesql-core = { path = "../../core", version = "0.10.1", features = [
	"index",
	"transaction",
	"alter-table",
	"metadata",
] }
utils = { package = "gluesql-utils", path = "../../utils", version = "0.10.1" }
async-trait = "0.1"
iter-enum = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
bincode = "1"
sled = "0.34"

[dev-dependencies]
test-suite = { package = "gluesql-test-suite", path = "../../test-suite", version = "0.10.1", features = [
	"index",
	"transaction",
	"alter-table",
	"metadata",
] }
criterion = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }

[[bench]]
name = "sled_benchmark"
harness = false
