name: JavaScript

on:
  push:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"
  pull_request:
    paths-ignore:
      - "docs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  js_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: browser-actions/setup-firefox@latest
      - name: Set up wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.0"
      - run: |
          cd pkg/javascript
          npm install
          wasm-pack build --target web
          wasm-pack build --target nodejs -- --no-default-features --features nodejs
          wasm-pack test --headless --firefox
          cd ../../

  js_storage_tests:
    name: Storage tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: browser-actions/setup-firefox@latest
      - name: Set up wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.0"
      - run: |
          cd storages/web-storage
          wasm-pack test --headless --firefox
          cd ../idb-storage
          WASM_BINDGEN_TEST_TIMEOUT=60 wasm-pack test --headless --firefox
          cd ../../
