name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number or step to bump"
        required: true
        default: "minor"

env:
  CARGO_TERM_COLOR: always

jobs:
  bump_version:
    name: Bump versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-release
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Bump versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cargo release version ${{ github.event.inputs.version }} --workspace --execute --no-confirm
          cd pkg/javascript
          NEW_VERSION=$(npm version ${{ github.event.inputs.version }}>&1)
          cd ../../
          NEW_BRANCH="prepare-release-$NEW_VERSION"
          git checkout -b $NEW_BRANCH
          git config --local user.email "taehoon.moon@outlook.com"
          git config --local user.name "Taehoon Moon"
          git add .
          git commit -m "Bump version to $NEW_VERSION"
          git push origin $NEW_BRANCH
          gh pr create --draft --title "Prepare release $NEW_VERSION" --body "Prepare release $NEW_VERSION" --repo $GITHUB_REPOSITORY
