name: Publish JavaScript

on:
  workflow_dispatch:
    inputs:
      # Latest commit to include with the release. If omitted, use the latest commit on the main branch.
      sha:
        description: Commit SHA
        type: string
      dry_run:
        description: Dry run
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_npm:
    name: to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Set up wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "v0.13.0"
      - run: |
          printf '\n[profile.release]\nopt-level = "s"\n' >> Cargo.toml
          cd pkg/javascript
          wasm-pack build --no-pack --target web --no-typescript --release --out-dir ./dist_web
          wasm-pack build --no-pack --target nodejs --no-typescript --release --out-dir ./dist_nodejs -- --no-default-features --features nodejs
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            npm publish --provenance --dry-run
          else
            npm publish --provenance
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
