name: Publish JavaScript

on:
  workflow_dispatch:
    inputs:
      # Latest commit to include with the release. If omitted, use the latest commit on the main branch.
      sha:
        description: Commit SHA
        type: string
 
env:
  CARGO_TERM_COLOR: always

jobs:
  publish_to_npm:
    name: to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up wasm pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'v0.12.1'
      - run: |
          echo "\n[profile.release]\nopt-level = \"s\"" >> Cargo.toml
          cd pkg/javascript
          wasm-pack build --no-pack --target web --no-typescript --release --out-dir ./dist_web
          wasm-pack build --no-pack --target nodejs --no-typescript --release --out-dir ./dist_nodejs -- --no-default-features --features nodejs
          npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
